spring:
  application:
    name: dynamic-datasource-starter-test
    profiles:
      active: dev
dynamic:
  datasource:
    ####数据源默认数据库
    username: cnr_core
    initialSize: 3
    ############# c3p0 连接池配置  #################
    c3p0:
      ####失败后尝试次数
      acquireRetryAttempts: 3
      ####超时等待时间，这是单位s
      maxIdleTime: 60
      ####当连接池中的连接耗尽的时候c3p0一次同时获取的连接数
      acquireIncrement: 3

    trends:
      enabled: true
    single:
      enabled: false
    type:
      c3p0: true


mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  typeAliasesPackage: com.cfm.datasource.entity


